### ISSUE TITLE
Updates to Course Template

### ISSUE THREAD

**Issue by qwinters** [qwinters/texwork-template#16]
- [ ] Change the file format structure to look like:
```yaml
courses:
    YYYY-(WIN|SPR|SUM|AUT)-{department_code}-{course_number}-{abrv_title}:
        - course.tex: pdf output ignored
        - references.bib: pre-populate this with double checked examples
        - lectures: 
            - lecture-XX:
                - title-lec-XX-notes.tex: pdf output ignored, only compiled through course.tex
                - title-lec-XX-refs.bib: Individual refs sourced within the lecture notes only
                - code: *.{py, java, m, cpp, scala, ...}
                - figures: *.pdf_tex
                - images: *.{png, jpeg, tiff, ...}         
        - homework:
            - homework-XX:
                - title-homework-XX-problems.pdf: pdf here has to be manually force added
                - title-homework-XX-solutions.tex: pdf output is ignored
                - code: *.{py, java, m, cpp, scala, ...}
                - figures: *.pdf_tex
                - images: *.{png, jpeg, tiff, ...}     
```
- [ ] Double check reference format
- [ ] Add pdf to gitignore for everywhere along with all latex output types (homework pdf problems have to be specifically force added!) 
- [ ] Check that bibliographies are properly compiled into one final source at the end of the document
- [ ] Check that bibliographies can also be compiled individually per section
- [ ] Check that reference works across folders (e.g. lecture-01 can refer to theorems and labels from lecture-02 etc)
- [ ] Reset-up headers for course tex file
- [ ] Reset-up headers for homework tex file
- [ ] Verify that homework can do problem and sub-problem labeling
- [ ] Find way to reference, but not include homework files into course (e.g. so that you can refer to Problem 1 (a) on Homework Assignment 1 in lecture notes)
- [ ] Reset create script to deal with proper new format for things
- [ ] Change compile script to delete all files that are .gitignored after compiling, except for pdf!
- [ ] Add appendixes to the course.tex file for all the main appendixes you need
- [ ] Add flag to compile script `--breakdown-pdfs` to add templated `xcomment` code to preamble and create specific pdfs for theorems-only, theorem-and-proof-only, definitions-only, definitions-and-examples-and-counterexamples-only PDFs
