### ISSUE TITLE
Add vita document template

### ISSUE THREAD

**Issue by qwinters** [qwinters/texwork-template#20]
- [ ] General layout
```yaml
vita:
    - styles: {....}.sty
    - assets: headshot.png
    - sections:
        - education: 
            - education.tex
            - certifications.tex
            - coursework.tex
        - experience
            - academic-appointments.tex
            - research.tex
            - teaching.tex
            - professional.tex
        - research
            - research-interests.tex  
            - preprints.tex
            - articles.tex
            - conference-presentations.tex
            - colloquia-seminars-and-workshops.tex
            - patents.tex
            - public-coursenotes.tex
            - expository-writing.tex
        - honors
            - memberships.tex
            - grants.tex
            - honors-and-awards.tex
        - general
            - contact-information.tex
            - biographical-information.tex
            - programming-skills.tex
            - language-skills.tex
            - interests-and-hobbies.tex
            - references.tex
    - vita-short.tex
    - vita-long.tex
```
- [ ] Verify vita styles are open
- [ ] Script to update your vita information with all of you current preprint, in-progress, and published research
